sudo: required
cache:
  apt: true
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
  - $HOME/.sbt/0.13/staging
addons:
  apt:
    packages:
    - aspell
    - aspell-en
language: scala
scala:
   - 2.12.0
jdk:
  - oraclejdk8
script:
  - ./sbt test
  - ./sbt test -Dorg.nlogo.is3d=true
  # Tricks to avoid unnecessary cache updates (see http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html)
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
notifications:
  email:
    - nicolaspayette@gmail.com
